[build]
  publish = "public"
  command = "composer update --no-dev --optimize-autoloader --no-interaction && php artisan config:cache && php artisan route:cache && php artisan view:cache"

[build.environment]
  PHP_VERSION = "8.3"
